version: '3.9'

services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  # The manger service will have the 3000 port
  manager:
    build: ./manager
    command: bash -lc 'bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: development
      AUTH_SERVICE_URL: http://auth_service:3001
      REDIS_URL: redis://redis:6379/0
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - auth_service
    volumes:
      - ./manager:/app

  manager_worker:
    build: ./manager
    command: bash -lc "bundle exec sidekiq"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: development
      AUTH_SERVICE_URL: http://auth_service:3001
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./manager:/app
  
  # It'll have the port 3001
  auth_service:
    build: ./auth_service
    command: ["bash", "-lc", "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3001"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: development
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - ./auth_service:/app
  
  # It'll have the port 3002
  notification_service:
    build: ./notification_service
    command: ["bash", "-lc", "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0 -p 3002"]
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: development
    ports:
      - '3002:3002'
    depends_on:
      - 'postgres'
      - 'manager'
      - 'manager_worker'
    volumes:
      - ./notification_service:/app

volumes:
  postgres_data: