default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>

development:
  <<: *default
  database: notification_service_development

test:
  <<: *default
  database: notification_service_test

production:
  <<: *default
  database: notification_service_production
  username: notification_service
  password: <%= ENV["NOTIFICATION_SERVICE_DATABASE_PASSWORD"] %>