default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>

development:
  <<: *default
  database: auth_service_development

test:
  <<: *default
  database: auth_service_test

production:
  <<: *default
  database: auth_service_production
  username: auth_service
  password: <%= ENV["AUTH_SERVICE_DATABASE_PASSWORD"] %>
